baseURL = "https://docs.jeelabs.org/"
languageCode = "en-gb"
title = "JeeLabs Docs"
theme = "hugo-theme-learn"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
themeVariant = "blue"
editURL = "https://github.com/jeelabs/docs/edit/master/content/"
